import { useEffect } from "react";
import { Link } from "react-router-dom";
import { Header, NewsletterSection, ContactSection, Footer } from "./App";

export default function BlogArticle4() {
  useEffect(() => {
    document.title = "AI Governance as Collective Action — Accentrop";
  }, []);

  return (
    <div className="min-h-screen flex flex-col">
      <Header />
      <main className="flex-1 max-w-3xl mx-auto px-6 py-16 w-full">
        <Link
          to="/blog-articles"
          className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-primary transition-colors mb-8 group"
        >
          <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" className="group-hover:-translate-x-1 transition-transform">
            <path d="M19 12H5"/><path d="M12 5l-7 7 7 7"/>
          </svg>
          More Blog Articles
        </Link>

        <div className="flex items-center gap-3 mb-3">
          <span className="text-xs font-semibold uppercase tracking-widest text-primary bg-primary/10 rounded-full px-3 py-0.5">Collective Responsibility</span>
        </div>

        <h1 className="text-3xl sm:text-4xl font-black text-primary mb-10 leading-tight">
          AI Governance as Collective Action: How Communities Can Shape AI's Future
        </h1>

        <div className="bg-muted rounded-2xl px-6 sm:px-10 py-8 space-y-8 text-foreground leading-relaxed">
          <p>
            AI governance is often framed as a task for experts — regulators, ethicists, and large technology companies. But that framing misses something fundamental: the people most affected by AI systems are rarely in the room when decisions are made. Effective governance is not possible without the voices of the communities AI actually touches.
          </p>

          <hr className="border-border" />

          <section>
            <h2 className="text-2xl font-bold text-foreground mb-4">Why Collective Action Matters</h2>
            <p className="mb-4">
              AI systems are built on data generated by billions of people — their language, their behaviour, their creative work, their decisions. Yet the benefits of AI have concentrated narrowly, and the harms have often landed on those with the least power to challenge them. Collective action in AI governance is the mechanism by which that imbalance can be corrected.
            </p>
            <ul className="space-y-3 mb-6">
              {[
                { term: "Diversity of Perspective", def: "Communities experiencing AI's effects first-hand — whether workers displaced by automation or minorities affected by biased systems — hold knowledge that no lab or policy team can replicate." },
                { term: "Accountability at Scale", def: "Regulators cannot monitor every AI deployment. Community-level reporting creates distributed oversight that reaches further than any single institution." },
                { term: "Legitimacy", def: "Governance frameworks gain legitimacy when they reflect the values and concerns of the people they are meant to protect — not just the preferences of developers or shareholders." },
              ].map(({ term, def }) => (
                <li key={term} className="flex gap-2">
                  <span className="mt-1.5 shrink-0 w-2 h-2 rounded-full bg-primary" />
                  <span><strong className="text-foreground">{term}:</strong> {def}</span>
                </li>
              ))}
            </ul>
          </section>

          <hr className="border-border" />

          <section>
            <h2 className="text-2xl font-bold text-foreground mb-4">What Collective Participation Looks Like</h2>
            <ul className="space-y-3 mb-6">
              {[
                { term: "Incident Reporting", def: "When individuals document AI failures — bias, hallucinations, privacy violations — that data becomes evidence regulators and developers can act on. Reporting is governance." },
                { term: "Public Comment", def: "Most regulatory frameworks include public consultation periods. Organised communities can submit responses that represent the experiences of many, not just professional lobbyists." },
                { term: "Civil Society Organisations", def: "NGOs, academic institutions, and advocacy groups can translate community experiences into policy language and maintain pressure on both companies and governments." },
                { term: "Open Standards Participation", def: "International standards bodies that shape AI technical requirements accept public input. Contributing to these processes is a form of governance participation available to anyone." },
                { term: "Local Policy Engagement", def: "City and regional governments are increasingly making decisions about AI in public services — policing, benefits, planning. Local advocacy can directly influence these decisions." },
              ].map(({ term, def }) => (
                <li key={term} className="flex gap-2">
                  <span className="mt-1.5 shrink-0 w-2 h-2 rounded-full bg-primary/60" />
                  <span><strong className="text-foreground">{term}:</strong> {def}</span>
                </li>
              ))}
            </ul>
          </section>

          <hr className="border-border" />

          <section>
            <h2 className="text-2xl font-bold text-foreground mb-4">The Role of Platforms Like Accentrop</h2>
            <p className="mb-4">
              Tools that lower the barrier to participation make collective action possible at scale. When anyone — regardless of technical background — can report an AI experience, assess an AI risk, or contribute data about how AI performs in their context, the governance ecosystem becomes richer and more representative.
            </p>
            <p className="mb-4">
              This is not an abstract ambition. Every report filed, every risk assessment submitted, and every data point contributed adds to a growing record that can inform policy, guide developers, and give communities evidence of what is actually happening with AI in their lives.
            </p>
            <p className="bg-card rounded-lg px-5 py-4 text-sm font-medium text-muted-foreground border border-border">
              <strong className="text-foreground">The Invitation:</strong> AI governance is not waiting for permission to include you. The tools are here. The mechanisms exist. The question is whether enough people choose to use them — and whether those already in the conversation make room for those who are not.
            </p>
          </section>
        </div>

        <div className="mt-10 flex items-center justify-between">
          <Link
            to="/blog/ai-governance-accountability"
            className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-primary transition-colors group"
          >
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" className="group-hover:-translate-x-1 transition-transform">
              <path d="M19 12H5"/><path d="M12 5l-7 7 7 7"/>
            </svg>
            Previous Article
          </Link>
          <Link
            to="/blog-articles"
            className="inline-flex items-center gap-1.5 text-sm font-bold text-primary hover:text-primary/80 transition-colors"
          >
            All Articles
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
              <path d="M5 12h14"/><path d="m12 5 7 7-7 7"/>
            </svg>
          </Link>
        </div>
      </main>
      <NewsletterSection />
      <ContactSection />
      <Footer />
    </div>
  );
}
