import { useEffect, useRef, useState } from "react";
import { Link } from "react-router-dom";
import jsPDF from "jspdf";
import { Header, NewsletterSection, ContactSection, Footer } from "./App";

const QUESTION_PREFIX = "Within the past one month, how often was it reported by users that your company's";

const QUESTIONS = [
  "AI produced incorrect or fabricated information (hallucinations)?",
  "AI violated user data privacy or leaked sensitive information?",
  "AI produced biased or discriminatory responses?",
  "AI exceeded its defined operational boundaries or instructions?",
  "AI generated deepfake or synthetic media without clear disclosure?",
  "AI failed to meet accessibility needs for users with disabilities?",
  "AI generated insecure code or security-compromising recommendations?",
  "AI infrastructure caused significant local environmental or energy impact?",
];

const FREQUENCY_LABELS = ["Never", "Rarely", "Sometimes", "Often", "Always"];
const FREQUENCY_COLORS = [
  "text-green-600 dark:text-green-400",
  "text-teal-600 dark:text-teal-400",
  "text-yellow-600 dark:text-yellow-400",
  "text-orange-500 dark:text-orange-400",
  "text-red-600 dark:text-red-400",
];

type Status = "idle" | "waiting" | "ready" | "error";

const DISCLAIMER =
  "DISCLAIMER: This report is auto-generated by AI for informational and awareness purposes only and does not constitute legal, professional, or regulatory advice. " +
  "Accentrop and Cryp Tok Solutions accept no liability for decisions or actions taken based on this report. " +
  "Always consult qualified professionals before implementing risk management decisions.";

function downloadPDF(reportText: string) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const margin = 16;
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const maxW = pageW - margin * 2;
  let y = margin;

  // Disclaimer box
  doc.setFillColor(245, 245, 245);
  doc.setFontSize(8);
  doc.setFont("helvetica", "italic");
  doc.setTextColor(90);
  const disclaimerLines = doc.splitTextToSize(DISCLAIMER, maxW - 6);
  const boxH = disclaimerLines.length * 4 + 4;
  doc.roundedRect(margin, y, maxW, boxH, 2, 2, "F");
  doc.text(disclaimerLines, margin + 3, y + 4);
  y += boxH + 8;

  // Report body
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(30);
  const bodyLines = doc.splitTextToSize(reportText, maxW);
  for (const line of bodyLines) {
    if (y > pageH - margin) {
      doc.addPage();
      y = margin;
    }
    doc.text(line, margin, y);
    y += 5;
  }

  doc.save("ai-risk-management-report.pdf");
}

function CopyButton({ text }: { text: string }) {
  const [copied, setCopied] = useState(false);
  return (
    <button
      onClick={() => {
        navigator.clipboard.writeText(text).then(() => {
          setCopied(true);
          setTimeout(() => setCopied(false), 2000);
        });
      }}
      className="inline-flex items-center gap-1.5 text-xs text-muted-foreground hover:text-primary transition-colors border border-border rounded-lg px-3 py-1.5"
    >
      {copied ? (
        <>
          <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><polyline points="20 6 9 17 4 12"/></svg>
          Copied
        </>
      ) : (
        <>
          <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><rect width="14" height="14" x="8" y="8" rx="2" ry="2"/><path d="M4 16c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2h10c1.1 0 2 .9 2 2"/></svg>
          Copy report
        </>
      )}
    </button>
  );
}

function PdfButton({ text }: { text: string }) {
  return (
    <button
      onClick={() => downloadPDF(text)}
      className="inline-flex items-center gap-1.5 text-xs text-muted-foreground hover:text-primary transition-colors border border-border rounded-lg px-3 py-1.5"
    >
      <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
        <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/>
        <polyline points="14 2 14 8 20 8"/>
        <line x1="12" y1="18" x2="12" y2="12"/>
        <line x1="9" y1="15" x2="15" y2="15"/>
      </svg>
      Download PDF
    </button>
  );
}

export default function RiskSliderPage() {
  useEffect(() => {
    document.title = "AI Risk Management Slider — Accentrop";
  }, []);

  const [sliders, setSliders] = useState<number[]>(QUESTIONS.map(() => 0));
  const [comments, setComments] = useState<string[]>(QUESTIONS.map(() => ""));
  const [openComment, setOpenComment] = useState<boolean[]>(QUESTIONS.map(() => false));
  const [status, setStatus] = useState<Status>("idle");
  const [report, setReport] = useState("");
  const [reportExpanded, setReportExpanded] = useState(false);
  const [errorMsg, setErrorMsg] = useState("");
  const timerRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  const reportRef = useRef<HTMLDivElement>(null);

  function splitReport(text: string): { preview: string; rest: string } {
    const markers = ["\n2.", "\n**2", "\n## 2", "\n### 2", "\nRisk Assessment", "\n2 "];
    for (const marker of markers) {
      const idx = text.indexOf(marker);
      if (idx > 80) {
        return { preview: text.slice(0, idx).trim(), rest: text.slice(idx).trim() };
      }
    }
    const lines = text.split("\n");
    const cutLine = Math.min(8, lines.length);
    return {
      preview: lines.slice(0, cutLine).join("\n").trim(),
      rest: lines.slice(cutLine).join("\n").trim(),
    };
  }

  async function handleGenerate() {
    setStatus("waiting");
    setReport("");
    setErrorMsg("");

    const BASE = import.meta.env.BASE_URL.replace(/\/$/, "");
    let generatedReport = "";

    try {
      const res = await fetch(`${BASE}/api/risk-report`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ sliders, comments }),
      });
      if (!res.ok) throw new Error("API error");
      const data = (await res.json()) as { report: string };
      generatedReport = data.report;
    } catch {
      setStatus("error");
      setErrorMsg("Something went wrong generating your report. Please try again.");
      return;
    }

    timerRef.current = setTimeout(() => {
      setReport(generatedReport);
      setStatus("ready");
      setTimeout(() => reportRef.current?.scrollIntoView({ behavior: "smooth" }), 100);
    }, 30000);
  }

  useEffect(() => () => { if (timerRef.current) clearTimeout(timerRef.current); }, []);

  return (
    <div className="min-h-screen flex flex-col">
      <Header />
      <main className="flex-1 max-w-3xl mx-auto px-6 py-16 w-full">
        <Link
          to="/"
          className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-primary transition-colors mb-8 group"
        >
          <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" className="group-hover:-translate-x-1 transition-transform">
            <path d="M19 12H5"/><path d="M12 5l-7 7 7 7"/>
          </svg>
          Back
        </Link>
        {/* Intro */}
        <p className="text-xs uppercase tracking-widest text-muted-foreground mb-3 font-semibold">AI Risk</p>
        <h1 className="text-3xl sm:text-4xl font-black text-primary mb-1 leading-tight">
          AI Risk Management Slider
        </h1>
        <p className="text-sm text-muted-foreground mb-4">(for companies)</p>
        <p className="text-base text-muted-foreground leading-relaxed mb-10 max-w-2xl">
          Help your company reduce or mitigate AI related risk by providing risk assessment reports to your stakeholders and the development teams, at least once every month.
        </p>

        {/* Sliders */}
        <div className="bg-muted rounded-2xl px-6 sm:px-8 py-8 space-y-8 mb-8">
          {QUESTIONS.map((question, i) => (
            <div key={i}>
              <div className="flex items-start justify-between gap-4 mb-3">
                <p className="text-sm font-semibold text-foreground leading-snug">
                  <span className="font-normal text-muted-foreground">{QUESTION_PREFIX} </span>
                  {question}
                </p>
                <span className={`text-sm font-bold shrink-0 w-[6.5rem] text-right ${FREQUENCY_COLORS[sliders[i]]}`}>
                  {FREQUENCY_LABELS[sliders[i]]}
                </span>
              </div>
              <input
                type="range"
                min={0}
                max={4}
                step={1}
                value={sliders[i]}
                onChange={(e) =>
                  setSliders((prev) => {
                    const next = [...prev];
                    next[i] = Number(e.target.value);
                    return next;
                  })
                }
                className="w-full accent-primary h-2 cursor-pointer"
              />
              <div className="flex justify-between mt-1 mb-3">
                {FREQUENCY_LABELS.map((label) => (
                  <span key={label} className="text-[10px] text-muted-foreground">{label}</span>
                ))}
              </div>

              {/* Comment accordion */}
              <button
                type="button"
                onClick={() =>
                  setOpenComment((prev) => {
                    const next = [...prev];
                    next[i] = !next[i];
                    return next;
                  })
                }
                className="w-full flex items-center justify-between text-left px-3 py-2 rounded-lg border border-border bg-background text-sm text-muted-foreground hover:border-primary/50 transition-colors"
              >
                <span className={comments[i] ? "text-foreground" : ""}>
                  {comments[i] ? comments[i].slice(0, 60) + (comments[i].length > 60 ? "…" : "") : "Add comments"}
                </span>
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  width="14"
                  height="14"
                  viewBox="0 0 24 24"
                  fill="none"
                  stroke="currentColor"
                  strokeWidth="2.5"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  className={`shrink-0 transition-transform duration-200 ${openComment[i] ? "rotate-180" : ""}`}
                >
                  <path d="m6 9 6 6 6-6"/>
                </svg>
              </button>

              {openComment[i] && (
                <textarea
                  autoFocus
                  rows={3}
                  value={comments[i]}
                  onChange={(e) =>
                    setComments((prev) => {
                      const next = [...prev];
                      next[i] = e.target.value;
                      return next;
                    })
                  }
                  placeholder="Add any context or notes about this risk area…"
                  className="w-full mt-1 px-3 py-2 rounded-lg border border-primary/50 bg-background text-sm text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-primary/30 resize-none transition-all"
                />
              )}
            </div>
          ))}
        </div>

        {/* Generate button */}
        <button
          onClick={handleGenerate}
          disabled={status === "waiting"}
          className="w-full rounded-xl bg-primary text-white font-bold text-base py-3.5 hover:bg-primary/90 transition-colors shadow-md disabled:opacity-60 disabled:cursor-not-allowed mb-8"
        >
          {status === "waiting" ? "Generating…" : "Generate Risk Assessment Report"}
        </button>

        {/* Placeholder while waiting */}
        {(status === "waiting" || status === "ready") && (
          <div className="bg-muted rounded-2xl px-6 sm:px-8 py-8 mb-6">
            <p className="text-base font-semibold text-foreground mb-2">
              Your risk assessment report will be displayed here momentarily.
            </p>
            <p className="text-sm text-muted-foreground leading-relaxed">
              While waiting, head over to{" "}
              <a
                href="https://captaintok.com"
                target="_blank"
                rel="noopener noreferrer"
                className="text-primary underline underline-offset-2 font-semibold hover:text-primary/80"
              >
                captaintok.com
              </a>{" "}
              to purchase one of our ebooks — we need funds to continue to build and maintain these AI Governance apps.
            </p>
          </div>
        )}

        {/* Error */}
        {status === "error" && (
          <p className="text-sm text-red-600 dark:text-red-400 mb-6">{errorMsg}</p>
        )}

        {/* Report */}
        {status === "ready" && report && (() => {
          const { preview, rest } = splitReport(report);
          return (
          <div ref={reportRef} className="space-y-4">
            <div className="flex justify-end gap-2">
              <CopyButton text={report} />
              <PdfButton text={report} />
            </div>
            <div className="rounded-xl border border-amber-200 bg-amber-50 dark:border-amber-900/40 dark:bg-amber-950/20 px-4 py-3 text-xs text-amber-800 dark:text-amber-300 leading-relaxed">
              {DISCLAIMER}
            </div>
            <div className="bg-muted rounded-2xl px-6 sm:px-8 py-8 text-sm text-foreground leading-relaxed font-mono">
              <p className="whitespace-pre-wrap">{preview}</p>

              {rest && (
                <>
                  {reportExpanded && (
                    <p className="whitespace-pre-wrap mt-4">{rest}</p>
                  )}
                  <button
                    type="button"
                    onClick={() => setReportExpanded((v) => !v)}
                    className="mt-5 flex items-center gap-2 text-xs font-semibold text-primary hover:text-primary/80 transition-colors"
                  >
                    <svg
                      xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24"
                      fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"
                      className={`transition-transform duration-200 ${reportExpanded ? "rotate-180" : ""}`}
                    >
                      <path d="m6 9 6 6 6-6"/>
                    </svg>
                    {reportExpanded ? "Collapse report" : "Show full report — Risk Assessment, Recommended Actions & Monitoring"}
                  </button>
                </>
              )}
            </div>
            <div className="flex justify-end gap-2">
              <CopyButton text={report} />
              <PdfButton text={report} />
            </div>
            <p className="text-center text-sm text-muted-foreground pt-2">
              <a
                href="https://captaintok.com"
                target="_blank"
                rel="noopener noreferrer"
                className="text-primary font-semibold underline underline-offset-2 hover:text-primary/80"
              >
                Download ebook at Captaintok.com
              </a>
            </p>
          </div>
          );
        })()}
      </main>
      <NewsletterSection />
      <ContactSection />
      <Footer />
    </div>
  );
}
